# docker/docker-compose.yml
version: '3'
services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../server:/usr/src/app/server
      - ../client:/usr/src/app/client
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development